/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionRequest
 */
export interface ActionRequest {
    /**
     * 
     * @type {number}
     * @memberof ActionRequest
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ActionRequest
     */
    action?: ActionRequestActionEnum;
}


/**
 * @export
 */
export const ActionRequestActionEnum = {
    CreateItem: 'CREATE_ITEM',
    DeleteItem: 'DELETE_ITEM',
    ViewItem: 'VIEW_ITEM',
    MoveItem: 'MOVE_ITEM'
} as const;
export type ActionRequestActionEnum = typeof ActionRequestActionEnum[keyof typeof ActionRequestActionEnum];


/**
 * Check if a given object implements the ActionRequest interface.
 */
export function instanceOfActionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActionRequestFromJSON(json: any): ActionRequest {
    return ActionRequestFromJSONTyped(json, false);
}

export function ActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'action': !exists(json, 'action') ? undefined : json['action'],
    };
}

export function ActionRequestToJSON(value?: ActionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'action': value.action,
    };
}

